# This file was generated by GoReleaser. DO NOT EDIT.
class Donner < Formula
  desc "Donner is a generic command wrapper. It let's you define strategies to wrap commands in things like 'docker-compose exec' or 'docker container run'."
  homepage ""
  version "0.1.1"

  if OS.mac?
    url "https://github.com/codetales/donner/releases/download/0.1.1/donner_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "25f97b3830e92113d1d8712ddb8086b29ae3478978680019c3b54fd52b2a55e0"
  elsif OS.linux?
    url "https://github.com/codetales/donner/releases/download/0.1.1/donner_0.1.1_Linux_x86_64.tar.gz"
    sha256 "c1f51f0fd21ffb82938e3b5c07ffd1113779865bdf94321d76850c1aae998aec"
  end

  def install
    bin.install "donner"
  end
end
