# This file was generated by GoReleaser. DO NOT EDIT.
class Donner < Formula
  desc "Donner is a generic command wrapper. It let's you define strategies to wrap commands in things like 'docker-compose exec' or 'docker container run'."
  homepage ""
  version "0.1.0"

  if OS.mac?
    url "https://github.com/codetales/donner/releases/download/0.1.0/donner_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "99819a07051cce4ed6f18878bac1db038cb503abb450765d9dd0e0f029bf9bb0"
  elsif OS.linux?
    url "https://github.com/codetales/donner/releases/download/0.1.0/donner_0.1.0_Linux_x86_64.tar.gz"
    sha256 "a767ec708e70cde9169a95c117c77405c9f610a2b2470ac9fdb33865da058eb7"
  end

  def install
    bin.install "donner"
  end
end
